### ISSUE TITLE
More or less ready for alpha

### ISSUE THREAD

**Issue by JPumphrey** [RefugeRestrooms/refugerestrooms-android#2]
Tagging @tkwidmer, and @glassresistor  who mentioned you'd be interested in some android dev/testing?

Getting close to an alpha MVP - do you folks want to take it for a spin? Obv you can build it yourselves, or I could look into using the Google Play beta channel or something. What do you think?

**Comment by thelseraphim** [comment]
Hey I'm interested in poking at this and wondered what the status of the project is -- particularly are the @JPumphrey and @msopinka versions merged? And how much investment is there in these clients so far?

**Comment by tkwidmer** [comment]
@thelseraphim 

@msopinka has been unresponsive about his version, which has been taken down from the android google play store, some users complained that they couldn't find it. I wanted him to merge with this repo, so it could be owned by the community but he never was willing to do that. That project was a bit further along than this one - which is unfortunate.

Which means, that this repo is where we should direct efforts.

**Comment by JPumphrey** [comment]
@tkwidmer Ah, I didn't realise that. I was still trying to find out the best way for the community to own this rather than putting it under my own dev account, when the other version went onto gp and got a fair bit of publicity. I just thought fair play to @msopinka.

I'm certainly happy to carry on working on this. I think I started setting up a gmail under the refuge-restrooms name, so we could put this up on the play store, maybe as a beta. AFAIR it's functional if not complete. Alternatively, if @msopinka's version is still on github, we can resubmit that (I think).

I should have some time this weekend when I can take a look at it. @thelseraphim have you managed to build either of them?

**Comment by tkwidmer** [comment]
@JPumphrey we already have a google play I think under the refugerestrooms@gmail.com account

**Comment by JPumphrey** [comment]
@tkwidmer do you have the login for that account? It looks like the recovery email is your email.

**Comment by JPumphrey** [comment]
@tkwidmer Cool, do you want me to access the account directly or send you the apps to upload yourself?

**Comment by hissingpanda** [comment]
I've been using the refuge restrooms api, and some of @JPumphrey 's server code here to make a similar app: https://github.com/hissingpanda/gnb

I'd like to try and merge our efforts as well into a refuge restrooms app; the focus of my app was just to find the nearest gender neutral bathroom from a user's location, so I think it could benefit from all of the search features that have been implemented here.

I'm hoping to roll this out on google play by the end of the month -- not much user testing has been done yet though, but I'm of the mindset that the sooner the release the better, then just fix things along the way.

**Comment by JPumphrey** [comment]
@hissingpanda  Yeah agreed, we could set up another google play account, refugerestroomsapps or something. We should aim for a single app to avoid confusion for users - they need too trust us. I don't have a lot of time to work on this, so I can't commit to merging in lots of code, but I think what we release should be under a refuge restrooms account and the org.refugerestrooms package name.

**Comment by hissingpanda** [comment]
@JPumphrey Alright, sounds good. I was planning on finishing up a few things for the app next week, so I'll also rename the package and setup another refuge restrooms account. 

I don't know the best way to merge these though, as the main activities are completely different, so I might just merge it to be what I have currently, and leave many of the current "view" files as extras to be added in later.. if that sounds alright (although I might try to throw in the search/detail view activities for the nav drawer if I have time). Then I'll look into getting it in google play if you all are satisfied with the state of it.

**Comment by JPumphrey** [comment]
@hissingpanda Cool :) It would be nice if it could have more RR branding - app name and purple colours, etc, but the overall look is nice.

**Comment by hissingpanda** [comment]
@JPumphrey Made a pull request! I also added updated screenshots with the refuge colors, and changed the app/project name.. etc. 

I want to finish the search locations feature before I submit it to google play, because otherwise the app is currently useless without gps enabled -- I haven't been able to get a user's location without gps as of yet -- but the search shouldn't take me long. Other than that, I've tested it a bit on three android devices and haven't run into any issues.. would've liked to do some more extensive testing though. Also, I put the original apps files in an "Alt" folder as a later reference.

If you have time, clone it and check it out, it should run fine (Google Maps API authorization might give you a problem, but hopefully not), otherwise hopefully I'll get this on the play store next week!

**Comment by tkwidmer** [comment]
<3 <3 <3

**Comment by hissingpanda** [comment]
:) Btw are there any promotional materials for refuge restrooms like flyers to print out? I'd like to put some up in some inclusive bathrooms around town.

**Comment by tkwidmer** [comment]
I don't think we have any fliers, we should totally make them and put them in the assets repo

**Comment by hissingpanda** [comment]
Yeah that would be awesome! 

I created a new developer account under refugerestroomsapp@gmail.com, and published the app under Beta Testing. I'll push it on the play store once this goes through and I double-check that it runs correctly. It should be available on Friday at the latest!

**Comment by tkwidmer** [comment]
I think I actually have a developer account for refugerestrooms@gmail.com

**Comment by tkwidmer** [comment]
oh scratch that. I have one under my personal email

**Comment by tkwidmer** [comment]
@hissingpanda can we make sure that I at least have access to that email / developer account. Since folks tend to come and go and help sporadically. I want to make sure I can give access and help push future builds when people make improvements. 

<3 Thanks so much for your hard work!

**Comment by hissingpanda** [comment]
@tkwidmer Yeah I'll send you an email giving you access, and the apk keystore pass. As you need it to update the app, but I didn't want to store it on git. 

I'm going to push the app live now, as it's working for everyone I've had try it... I'd like to add more things like a more info button and a detailed list view like @JPumphrey had made, but I think I'll have to come back to that in a month. Could I get write permissions to the git project though? So I can merge my PR, for anyone else who might come along. 

And of course! I really appreciate everything you've done with refuge :)

**Comment by hissingpanda** [comment]
https://play.google.com/store/apps/details?id=org.refugerestrooms
xD

Gave you access to the developer console and sent you the keystore pass. You just have to enter that when signing the apk from android studio.

**Comment by tkwidmer** [comment]
@hissingpanda invited you to the org
