### ISSUE TITLE
guide for new contributors

### ISSUE THREAD

**Issue by thelseraphim** [RefugeRestrooms/refugerestrooms-android#5]
Figuring out how to build or contribute to this project, as well as details like code-style and library footprint could be clarified in a CONTRIBUTING.md -- if I can figure it all out I'll write it myself but maybe one of the early contributors would find this easier to do.

**Comment by JPumphrey** [comment]
@thelseraphim It's still an eclipse project (I haven't looked at it for a few months), so you should be able to build it like any other. You can probably do import -> android code or whatever it is.

I'm not too worried about writing guidelines for code style for a project this size - I'm sure your code isn't horrible :) and I'd rather focus on code at this stage. If you're worried about committing, do a pull request.

But you'e right, I should update the readme with how to build the thing.

**Comment by JPumphrey** [comment]
@thelseraphim Ah, I should have looked at the code before answering (I don't get notifications for commits, maybe I should). It looks like @naimahm and @akembry have done a fair amount of work on this (thanks!), and it's now an Android Studio project. Still no harm in updating the readme, I'll do that.
