### ISSUE TITLE
Can't add bathrooms

### ISSUE THREAD

**Issue by hissingpanda** [RefugeRestrooms/refugerestrooms-android#52]
Within the Add a bathroom webview, the app reads, "We're sorry but something went wrong", and doesn't render the form. The form is working on the site.

**Comment by hissingpanda** [comment]
This appears to still be broken in the play store, despite working locally.
![screenshot_2017-08-27-02-03-52](https://user-images.githubusercontent.com/7660115/29754152-6543595a-8b34-11e7-9b1e-c9d3c08b9f29.png)

**Comment by hissingpanda** [comment]
Actually, upon re-install this appears to be working for me, but I've gotten a couple emails stating otherwise. Can anyone verify if the add a bathroom section is loading on v1.4.1? @christianlepson?

**Comment by mi-wood** [comment]
@hissingpanda could be https://github.com/RefugeRestrooms/refugerestrooms/issues/368. It's been throwing an error, but not every page load. Still haven't been able to debug it.

**Comment by hissingpanda** [comment]
@mi-wood ah that might be it. Strange that it's so sporadic
