### ISSUE TITLE
Cannot search a location (Android)

### ISSUE THREAD

**Issue by tkwidmer** [RefugeRestrooms/refugerestrooms-android#53]
![screen shot 2017-07-07 at 2 31 42 pm](https://user-images.githubusercontent.com/5265597/27977789-3085314c-6321-11e7-9a8a-aa20ab3cfaca.png)

Just had an exchange via FB with somebody who noticed a bug.

**Comment by christianlepson** [comment]
I'm almost finished fixing the search functionality. 

When the user searches an address, do we want to set their starting position (for the route to the restroom) to the address that they searched, or do we want to keep the user's current location as the starting position for the route?
