### ISSUE TITLE
Add translations (e.g. Spanish)

### ISSUE THREAD

**Issue by DeeDeeG** [RefugeRestrooms/refugerestrooms-android#57]
Hi all,

The web app is now translatable, and a Spanish translation is probably going to go live soon. There is also interest in seeing the mobile apps translated. If there is any way I or other contributors can help, that would be great. 

(I think we have an ability to signal boost about this via Twitter to try to get more people looking into it if need be.)

**Comment by hissingpanda** [comment]
I don't have the capacity to do this at the moment, but would be able to merge pull requests that others submit. So I think a call on Twitter would be great!

**Comment by DeeDeeG** [comment]
I found how translations are managed. I poked around in Android Studio, and was double-clicking on all the source files to see what tools the IDE brings up to work on those files.

When you double-click `strings.xml` (`app/src/main/res/values/strings.xml`), it brings up a translation editor.


Full documentation is here: https://developer.android.com/studio/write/translations-editor

but I find the translation editor, and even the raw files, reasonably straight-forward. 

---

Here's an example translated string (translated with Google Translate):

`app/src/main/res/values/strings.xml`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="add_bathroom_unisex">Unisex</string>
</resources>
```

`app/src/main/res/values-es/strings.xml`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="add_bathroom_unisex">Unisexo</string>
</resources>
```

**Comment by DeeDeeG** [comment]
I think we have [high-quality translations in the web repo](https://github.com/RefugeRestrooms/refugerestrooms/tree/develop/config/locales) that we can re-use, since many of the strings are verbatim from the website. (And we can of course give credit to the people who submitted the translations to the other repo.)

**Comment by thehme** [comment]
Hi all, I'd like to add a PR for a Spanish translation.

**Comment by DeeDeeG** [comment]
hi @thehme,

That would be most welcome! To add the Spanish translation, you can add a file in this repo at `app/src/main/res/values-es/strings.xml`; This requires adding a new folder `values-es/` in `app/src/main/res/`.

Then, you can copy everything from [`app/src/main/res/values/strings.xml`](https://github.com/RefugeRestrooms/refugerestrooms-android/blob/master/app/src/main/res/values/strings.xml) to the new `values-es/strings.xml` file.

Lastly, you can edit `values-es/strings.xml`, so as to change the text in quotes from English to Spanish. For example:

```xml
    <string name="bathroom">bathroom</string>
```
becomes:
```xml
    <string name="bathroom">baño</string>
```

You may also want to look at the translations for the web app here for guidance: https://github.com/RefugeRestrooms/refugerestrooms/tree/develop/config/locales/es

We will likely ask someone who has contributed translations to the web app if they can review your translations and perhaps give feedback.

Thanks again for your interest in translating the app!

**Comment by thehme** [comment]
Hi @DeeDeeG I created a PR at https://github.com/RefugeRestrooms/refugerestrooms-android/pull/77, I'll wait for reviews, thanks.

**Comment by hissingpanda** [comment]
Thanks for this @thehme! I'll try to test everything out this week and deploy

**Comment by hissingpanda** [comment]
PR is great - Tested it out in spanish on my device. Going to push live tonight. Thanks so much @thehme !
