### ISSUE TITLE
Increase "Target SDK Version" to ≥ 26 (or Play Store won't accept updates starting in November)

### ISSUE THREAD

**Issue by DeeDeeG** [RefugeRestrooms/refugerestrooms-android#58]
Hi,

I just read an article at Arstechnica.com about needing to update our "targeted SDK version" for the app. 

Here's the relevant part of the article I read:

> As was [previously announced](https://arstechnica.com/gadgets/2017/12/https://arstechnica.com/gadgets/2017/12/google-fights-fragmentation-new-android-features-to-be-forced-on-apps-in-2018/google-fights-fragmentation-new-android-features-to-be-forced-on-apps-in-2018/) in December, this year Google will finally force app developers to upgrade their apps to target a modern version of Android.
> . . .
> In September 2018, the Google Play Store will require all app updates to target Android API level 26, which corresponds to Android 8.0.

(Source: https://arstechnica.com/gadgets/2018/03/the-android-p-peanut-brittle-pez-pixy-stix-developer-preview-is-here/ (from the section: "Forcing app developers to target 'Modern Android'"))

I don't know how hard it is to target a new SDK version, but I wanted to post about it here regardless, since it would be needed if we had an update to post on the Play Store around that time (or any time afterwards).

The minimum "targeted SDK version" is going to be updated annually, reflecting the previous year's SDK version number. Late this year we have to target Oreo, late next year Android P, and so on. Or at least that's Google's plan for the moment.

(We can leave the "Minimum SDK version" for our app the same, so we don't need to drop support for older devices or anything like that.)

**Comment by hissingpanda** [comment]
Good looking out! It's pretty simple typically, might require updating some deprecated code though. Will keep this open to make sure this is changed for the next update

**Comment by DeeDeeG** [comment]
I think we actually have until November, since that's What Google themselves say about it:

>Google Play [will require](https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html) that _new apps_ target at least Android 8.0 (API level 26) from August 2018, and that app updates target Android 8.0 from November 2018.

Source: https://developer.android.com/distribute/best-practices/develop/target-sdk.html

**Comment by Carmen-Git-It** [comment]
Hey folks! I'm new to this project, but I wanted to start working on it with the newest SDK and libraries. I have my copy targetting API level 28 and compiling without error or complaint. I also have every library aside from greendao on the most recent version.

I say this because I'm planning to commit and create a pull request tonight after a couple more hours of testing. I didn't want you to find a pull request coming out of the blue with no context or explanation.

**Comment by DeeDeeG** [comment]
@Carmen-Git-It, thanks for your efforts and the heads up! Very cool!

(I think @hissingpanda has mostly been running this repository, and I would probably have a hard time reviewing the Pull Request. But as a maintainer (mostly over at the website repository) I wanted to let you know I saw your message, and it's much appreciated!!)

**Comment by Carmen-Git-It** [comment]
Hey thank you for the warm welcome @DeeDeeG! 

I just submitted the pull request and I'm excited to keep working on it :)
