### ISSUE TITLE
User Added Bathrooms Don't Show

### ISSUE THREAD

**Issue by hissingpanda** [RefugeRestrooms/refugerestrooms-android#59]
Haven't tested, but a lot of feedback indicating that when you add a bathroom via the app it doesn't appear on the map for you (even after several weeks).

**Comment by DeeDeeG** [comment]
I hope we can figure this out. Having been working on the web app side of things for a while, maybe I can help figure this out? (Although I'm not the back end person as much as other maintainers are.)

Is the app doing anything special to submit these restrooms, where the possibility to break things could be within the app?

**Comment by DeeDeeG** [comment]
Otherwise, on the web side, it could be #42. I wonder if @tkwidmer or @mi-wood can take a look at the logs and see if there are submissions being caught in the spam blocker? Maybe even try to submit a restroom to the production db with the Android app and see if it show up as blocked in the logs?

**Comment by hissingpanda** [comment]
@DeeDeeG  yeah it's just a web view of the the app, nothing else really going on there. It doesn't seem to be #42 as when that would happen regularly it would come back with the rejected error in the app. The current issue seems to indicate that it was successfully submitted but just never appear in the database. I'll check tonight if submissions are being added to the site and just not displayed in the app. To me it could be a caching issue or something, or the info is just being handled incorrectly in the app, barring any sort of manual moderation.

**Comment by hissingpanda** [comment]
So I added a bathroom via the app last night and it still doesn't show. I was able to find it's url though here: https://refugerestrooms.org/restrooms/45022

For whatever reason the map doesn't instantiate on that link, and the listing doesn't appear in search results so there seems to be some sort of manual moderation for showing on search? Same thing occurred when I added a bathroom via the web app itself. @tkwidmer @mi-wood do y'all know anything about this / is there a way to approve them?

**Comment by DeeDeeG** [comment]
Did you happen to use the "guess my location" button, or drop a pin on the map when submitting with the web app? That would help to narrow down what kinds of requests are getting sent to the API.

On another note: I notice we are on a "deprecated" older version of the javascript-based maps API. Regardless of whether it fixes this issue, I think we should update that.

**Comment by hissingpanda** [comment]
Ah nice catch. I didn't use the guess my location or dropping a pin. Simply entered the address in both the app and in the web version. So it would probably seem that guess my location and pin dropping are working because they establish a lat/lng and those are the entries that show up. Whereas the fields not filled are based on address alone. That's possibly something that broke with the now deprecated version of the API? I recall it working before from the app and without having to pin drop.

**Comment by DeeDeeG** [comment]
I made a pull request to update the Maps API for the web app.

https://github.com/RefugeRestrooms/refugerestrooms/pull/510

**Comment by DeeDeeG** [comment]
I suppose it's not a 100% foregone conclusion that bumping the maps API version will help.

But hopefully all the new entries will start coming in with valid latitude/longitude. I think that would be the thing to confirm this is fixed, however we get there.

**Comment by DeeDeeG** [comment]
I notice this app uses the experimental branch of the Maps API in one place?

https://github.com/RefugeRestrooms/refugerestrooms-android/blob/ef480ebbcee429302baa5edcd048dd0d9b79bac4/app/src/main/assets/directions.html#L12

Might be worth switching to the `quarterly` or `weekly` version number. (But I don't want to impose, since I haven't contributed over here much yet, other than popping into the issues now and then.)

**Comment by DeeDeeG** [comment]
This is fixed now for all new entries. The problem was the Maps API changed to requiring a key, whereas I believe they allowed a "free" tier of service with no key before. Their announcement of this change must have been subtle.

See https://github.com/RefugeRestrooms/refugerestrooms/issues/511 for all the details.

**Comment by Carmen-Git-It** [comment]
That's fantastic news @DeeDeeG!!
