### ISSUE TITLE
Recent Bathrooms Tab switching to Add Bathroom

### ISSUE THREAD

**Issue by hissingpanda** [RefugeRestrooms/refugerestrooms-android#62]
In nav drawer, selecting recent bathrooms instead takes the user to the add bathroom section.

Recent bathrooms was mainly for loading the 500(?) most recent bathrooms so that they were still viewable when offline.

**Comment by Carmen-Git-It** [comment]
Ah fixed it, sorry that was my fault. I was sloppy when editing the navigation fragment code and added a careless else case. Fixed it and it in #63 .
